import type { Metadata } from "next";
import { Ubuntu } from "next/font/google"
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";

const ubuntu = Ubuntu({
  weight: ["400","500", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Loms-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body
        className="">
          <main className="w-full">
            <NavBar />
              {children}
          </main>
      </body>
    </html>
  );
}
