import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import { Providers } from "./provider";
// import AuthRedirect from "@/components/AuthRedirect";
// import AuthInit from "@/components/AuthInit";


const ubuntu = Ubuntu({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Loms-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body className="flex flex-col min-h-screen">
        <Providers>
          {/* <AuthInit /> */}
          {/* <AuthRedirect /> */}
          <main className="flex-grow">
            <NavBar />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
